apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: default
spec:
  controllerNamePrefix: nginx
  ingressClassName: webapprouting.kubernetes.azure.com
  loadBalancerAnnotations: 
    service.beta.kubernetes.io/azure-dns-label-name: "binarydadwth"